version: "2"
services:
  dbdata:
    image: mdillon/postgis:9.6
    entrypoint: /bin/bash
    volumes:
      - /var/lib/postgresql
  db:
    image: mdillon/postgis:9.6
    ports:
      - "5432:5432"
    volumes:
      - ./data-loader:/data-loader
      # - ./dev/postgis/data:/var/lib/postgresql/data
    volumes_from:
      - dbdata
  geoserver:
    image: keithmoss/ealgis-geoserver:2.9.1
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
     - GEOSERVER_LOG_LOCATION=/opt/geoserver/data_dir/logs/geoserver.log
    volumes:
     - ./dev/geoserver/data:/opt/geoserver/data_dir
     - ./geoserver/setenv.sh:/usr/local/tomcat/bin/setenv.sh
     - ./geoserver/:/gs/ # Only needed the first time GeoServer runs
  frontend:
    build: frontend/
    command: webpack
    volumes:
      - ./frontend:/frontend
    ports:
      - "35729:35729"
  web:
    build: django/
    command: runserver
    volumes:
      - ./django/:/app
      - ./frontend:/frontend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    env_file:
      - web-variables.env
    depends_on:
      - db
      - geoserver
  nginx:
    build: nginx/
    volumes:
      - ./nginx:/app
      - ./nginx/web:/var/www/html
    depends_on:
      - geoserver
    ports:
      - "8443:443"
    environment:
      - GEOSERVER_HOST=geoserver
      - GEOSERVER_PORT=8080