version: "2"
services:
  dbdata:
    image: mdillon/postgis:9.6
    entrypoint: /bin/bash
    volumes:
      - /var/lib/postgresql
  db:
    image: mdillon/postgis:9.6
    ports:
      - "5432:5432"
    volumes:
      - ./data-loader:/data-loader

      # FOR DEVELOPMENT ONLY
      # Enable this mapping to inject the tweaked postgresql.conf file into our PostgreSQL container.
      # NB: PostgreSQL MUST already be initialised with at least one database before you enable this.
      # - ./db/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

      # Enable this mapping and create ./dev/pg_log/ to get easier access to PostgreSQL's log files for debugging.
      # - ./dev/pg_log/:/var/lib/postgresql/data/pg_log/
    volumes_from:
      - dbdata
  geoserver:
    image: keithmoss/ealgis-geoserver:2.9.1
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
     - GEOSERVER_LOG_LOCATION=/opt/geoserver/data_dir/logs/geoserver.log
    volumes:
      - ./geoserver/setenv.sh:/usr/local/tomcat/bin/setenv.sh

      # FOR DEVELOPMENT ONLY
      # For setting up GeoServer for the first time. Refer to ./README.md
      # - ./geoserver:/app

      # Enable this mapping and create ./dev/geoserver/ for easier access to GeoServer's data directory.
      # NB: This will cause GeoServer to create a NEW data directory.
      # - ./dev/geoserver/data:/opt/geoserver/data_dir
    entrypoint: /app/docker-entrypoint.sh
  frontend:
    build: frontend/
    command: webpack
    volumes:
      - ./frontend:/frontend
    ports:
      - "35729:35729"
  web:
    build: django/
    command: runserver
    volumes:
      - ./django/:/app
      - ./frontend:/frontend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    env_file:
      - web-variables.env
    depends_on:
      - db
      - geoserver
  nginx:
    build: nginx/
    volumes:
      - ./nginx:/app
      - ./nginx/web:/var/www/html
    depends_on:
      - geoserver
    ports:
      - "8443:443"
    environment:
      - GEOSERVER_HOST=geoserver
      - GEOSERVER_PORT=8080