data:
  image: debian:jessie
  volumes:
    - ./:/app
    - ./data/dev:/data
    - ./data/recipes:/recipes

# shares volume with other images so we can use COPY
db:
  image: angrygoat/postgis:latest
  environment:
    - POSTGRES_USER=ealgis
    - POSTGRES_PASSWORD=ealgis
  ports:
    - "5432"
  volumes_from:
    - data

geoserver:
    image: keithmoss/ealgis-geoserver:2.9.1
    expose:
      - "8080"
    ports:
      - "8080:8080"
    links:
      - db
    environment:
     - GEOSERVER_LOG_LOCATION=/opt/geoserver/data_dir/logs/geoserver.log
    volumes:
     - ./backend/geoserver/data:/opt/geoserver/data_dir
     - ./backend/geoserver/setenv.sh:/usr/local/tomcat/bin/setenv.sh

uwsgi:
  build: backend/
  volumes_from:
    - data
  links:
   - db
  ports:
    - "9000"

nginx:
  build: frontend/
  volumes_from:
    - data
  links:
    - uwsgi
    - geoserver
  ports:
    - "8443:443"
