version: '2'
services:
  db:
    image: mdillon/postgis:9.6
  web:
    build: .
    command: runserver
    volumes:
      - .:/app
      - ../frontend:/frontend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SOCIAL_AUTH_TWITTER_KEY
      - SOCIAL_AUTH_TWITTER_SECRET
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
      - SOCIAL_AUTH_FACEBOOK_KEY
      - SOCIAL_AUTH_FACEBOOK_SECRET
    depends_on:
      - db
